name: 작업
description: 내부 엔지니어링 작업 또는 유지보수 작업
title: "[작업] "
labels:
  - "type:task"
  - "needs-triage"
body:
  - type: textarea
    id: goal
    attributes:
      label: 목표
      description: 기대 결과를 작성해주세요.
      placeholder: "예: 중복 검사를 줄이기 위해 인증 미들웨어를 리팩터링합니다."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 작업 범위
      placeholder: |
        - [ ] 작업 항목 1
        - [ ] 작업 항목 2
        - [ ] 작업 항목 3
    validations:
      required: true

  - type: textarea
    id: done_criteria
    attributes:
      label: 완료 기준 (Definition of Done)
      placeholder: |
        - 테스트 추가/수정 완료
        - 필요 시 문서 업데이트 완료
        - 배포 후 모니터링 계획 수립
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - "P0 - 필수"
        - "P1 - 높음"
        - "P2 - 보통"
        - "P3 - 낮음"
    validations:
      required: true
